version: '2'

services:
  nginx:
    container_name: nginx2
    image: nginx
    restart: always
    ports:
      - "8080:8080"
#      - "443:443"
    volumes:
      - ../www:/data/www
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile-phpfpm
    container_name: php2
    image: hw/phpfpm
    restart: always
    ports:
      - "9000:9000"
      - "12307:12307"
      - "9527:9527"
    volumes:
      - ../www:/data/www
    depends_on:
      - db
      - redis
  db:
    container_name: mysql2
    image: mysql:5.7.12
    restart: always
    user: root
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - "3307:3307"
    volumes:
      - ../mysql:/var/lib/mysql
  redis:
    container_name: redis2
    image: redis:3.0.7-alpine
    restart: always
  sinopia2:
    container_name: sinopia2
    image:  keyvanfatehi/sinopia:latest
    ports:
      - "4873:4873"
    restart: always
    volumes:
      - ../sinopia/config.yaml:/opt/sinopia/config.yaml
      - ../sinopia/htpasswd:/opt/sinopia/htpasswd
